First review
alex-markin/mbou_algososh pull request #1
Opened 2023-10-31 20:48 UTC by alex-markin

2023-11-14 12:03 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Была проделана огромная работа 🔥.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле `UPPER_CASE`;

- По чек-листу: классы, описывающие работу структур данных, должны быть вынесены в отдельные файлы в папке соответствующего компонента `(т.е в одной папке с компонентом)`.

- По чек-листу: функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, должны быть вынесены в отдельные файлы utils.ts в папке соответствующего компонента `(т.е в одной папке с компонентом)`;

- Последовательность фибоначчи:

  - Отсчёт лучше начинать с 1, а не с нуля. <https://disk.yandex.com/i/aEUV0ocIOKJHtQ>;

  - Вы должны реализовать функцию `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи. Это утилитарная функция, поэтому она должна находится в `utils`, в той же папке, что и алгоритм, т.е. в `fibonacci-page`.

- Сортировка массива:

  - Поправьте анимацию (сейчас она рывками идёт) алгоритма при работе сортировки выбором. А также поставьте числовые значения для столбиков. <https://disk.yandex.com/i/3SemseFHQ9kJbA>;

- Стек:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма.

- Очередь:

  - <https://disk.yandex.com/i/gWrJloHGw0n3GQ> - Нужно поправить работу алгоритма, то появляются надписи `head` и `tail`, то их нет. Так должно быть, советую ещё раз ознакомиться с заданием <https://disk.yandex.com/i/5fL_bMY6SEDIKA>;

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма.

- Связный список:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма.

  - При нажатии "Добавить в `tail`" кружок должен быть сверху а не снизу. А при любом удалении (`head`, `tail`) кружок должен быть снизу;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const max = 19; // maximum value for input
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`.  А также лучше вынести за пределы компонента.

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      const result = fibonacci(inputValue as number);
**Надо исправить:**

Переименуйте `fibonacci` в `getFibonacciNumbers`.

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +  const initialValues = ["0", "34", "85", "65"]; // initial values for the list
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }
**Можно лучше:**

При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен не будет:

```js
if (someCondition) {
  return value;
}
return data;
```

Такой подход называется "ранний возврат" <https://habr.com/ru/post/348074/>

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +  const max = 4; // maximum value for input
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +  const maxHeigth: number = 340;
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/string/string.tsx
> +  const maxLength = 11; // maximum value for input
**Надо исправить:**

Константы принято записывать в `UPPER_CASE`

2023-11-14 12:03 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    renderedItems.length && setRenderedItems([]);
**Можно лучше:**

лучше тут использовать обычный `if`, читабельность будет выше.

2023-11-14 15:39 UTC, alex-markin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const max = 19; // maximum value for input
Исправил

2023-11-14 15:39 UTC, alex-markin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      const result = fibonacci(inputValue as number);
исправил

2023-11-14 15:40 UTC, alex-markin commented on src/components/list-page/list-page.tsx
> +  const initialValues = ["0", "34", "85", "65"]; // initial values for the list
Исправил

2023-11-14 15:41 UTC, alex-markin commented on src/components/queue-page/queue-page.tsx
> +  const max = 4; // maximum value for input
Исправил

2023-11-14 15:41 UTC, alex-markin commented on src/components/sorting-page/sorting-page.tsx
> +  const maxHeigth: number = 340;
Исправил

2023-11-14 15:41 UTC, alex-markin commented on src/components/string/string.tsx
> +  const maxLength = 11; // maximum value for input
Исправил

2023-11-15 13:24 UTC, alex-markin commented
Добрый день. Комментарии по тексту:

Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

App.test.tsx - **удалил, хотя заготовка то от Яндекс.Практикума )**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE; - **Вынес их отдельно.**

По чек-листу: классы, описывающие работу структур данных, должны быть вынесены в отдельные файлы в папке соответствующего компонента (т.е в одной папке с компонентом). - **исправил**

По чек-листу: функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, должны быть вынесены в отдельные файлы utils.ts в папке соответствующего компонента (т.е в одной папке с компонентом); - **исправил**

Последовательность фибоначчи:

Отсчёт лучше начинать с 1, а не с нуля. https://disk.yandex.com/i/aEUV0ocIOKJHtQ;

Вы должны реализовать функцию getFibonacciNumbers, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи. Это утилитарная функция, поэтому она должна находится в utils, в той же папке, что и алгоритм, т.е. в fibonacci-page. - **переименовал функцию, перенес в utils в папке компонента, рендеринг сделал с index > 0**

Сортировка массива:

Поправьте анимацию (сейчас она рывками идёт) алгоритма при работе сортировки выбором. А также поставьте числовые значения для столбиков. https://disk.yandex.com/i/3SemseFHQ9kJbA; - **исправил**

Стек:
По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. - **поправил**

Очередь:
https://disk.yandex.com/i/gWrJloHGw0n3GQ - Нужно поправить работу алгоритма, то появляются надписи head и tail, то их нет. Так должно быть, советую ещё раз ознакомиться с заданием https://disk.yandex.com/i/5fL_bMY6SEDIKA; - **исправил**

По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. - **поправил**

Связный список:

По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. - **исправил**
 
При нажатии "Добавить в tail" кружок должен быть сверху а не снизу. А при любом удалении (head, tail) кружок должен быть снизу; - **исправил** 

Сделает код лучше:
Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален;

2023-11-15 13:27 UTC, alex-markin commented on src/components/list-page/list-page.tsx
> +    }
исправил в большинстве случаев

2023-11-15 18:12 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа 🔥.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-11-15 18:12 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +              disabled={tailIndex === MAX_LENGTH - 1 || !inputValue || isGlobalLoadingActive(isLoading)}
**Можно лучше:**

большие условия лучше выносить в отдельную переменную), чтобы было понятно, за что это условие отвечает.

2023-11-15 18:12 UTC, ArslanMustafin commented on src/constants/fibonacci.ts
> +export const MAX_INPUT_VALUE = 19; // maximum value for input
**Вы молодец:**

Круто что оставляете комментарии)

2023-11-16 16:02 UTC, merged